#model_select
model_name: 'allenai/longformer-large-4096'
#data
# model_name, data_dir, train_dir, tokenizer, max_len, has_labels, label_subtokens, batch_size, shuffle, num_workers
train_dir : '/root/projects/feedback_prize/data/process_data/all_train_texts_10.csv'
train_label : '/root/projects/feedback_prize/data/train.csv'
max_len: 1600
has_labels: True
label_subtokens: True
batch_size: 2
num_workers: 0
val_fold: 0

#model
num_labels: 15
learning_rate: 2e-6

#train
gpus: -1
ckpt: ~
num_epochs: 100